version: '3.8'

volumes:
  static:
  data:

networks:
  app-network:
    driver: bridge

services:
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - ./data:/data
      - static:/static
    networks:
      - app-network
    container_name: backend

  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - 8000:80
      - 8001:443
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - static:/static
      - ./ssl:/ssl
    networks:
      - app-network
    depends_on:
      - backend