volumes:
  static:
  data:

services:
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - ./data:/data
      - static:/static
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - 8000:80
      - 8001:443
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - static:/static
      - ./ssl:/ssl