version: '3.8'

volumes:
  backend_static:
  data:

networks:
  app-network:
    driver: bridge

services:
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - data:/data
      - backend_static:/static
    networks:
      - app-network
    container_name: backend
    environment:
      - STATIC_ROOT=/static
      - DATABASE_NAME=/data/db.sqlite3
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - 8000:80
      - 8001:443
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - backend_static:/backend_static
      - ./frontend:/frontend_static
      - ./ssl:/ssl
    networks:
      - app-network
